crm/admin_panel/urls.py
from django.urls import path

from .views import (NewClothesView, UpdateClothesView, 
                    AllClothesView, AllOrderView, 
                    CompleteOrderView,RemoveClothesView)

app_name = 'admin_panel'

urlpatterns = [
    path('new_clothes/', NewClothesView.as_view(), name='new_clothes'),
    path('update_clohes/<int:pk>/', UpdateClothesView.as_view(), name='update_clothes'),
    path('remove_clothes/<int:pk>/', RemoveClothesView.as_view(), name='remove_clothes'),
    path('all_clothes/', AllClothesView.as_view(), name='all_clothes'),
    path('all_order/',AllOrderView.as_view(), name='all_order'),
    path('all_order/<int:filter>/',AllOrderView.as_view(), name='all_order_with_param'),
    path('complete_order/', CompleteOrderView.as_view(), name='complete_order'),
]

crm/crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('admin_panel.urls')),
    path('', include('user_permission.urls')),
]


urlpatterns += static( settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crm/user_permission/urls.py
from django.urls import path

from .views import (NewUserView, UpdateUserView, RemoveUserView,AllUserView,
                LoginUserView,LogoutUserView)

app_name = 'user_permission'

urlpatterns = [
    path('all_user/', AllUserView.as_view(), name='all_user'),
    path('new_user/', NewUserView.as_view(), name='new_user'),
    path('update_user/<int:pk>/', UpdateUserView.as_view(), name='update_user'),
    path('remove_user/<int:pk>/', RemoveUserView.as_view(), name='remove_user'),
    path('login/', LoginUserView.as_view(),name='login'),
    path('logout/',LogoutUserView.as_view(),name='logout')
]

crm/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{NAME_SITE}} - {% block name_page %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
    {% block body %}
        {% block nav %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">{{name_site}}</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownClothes" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Одежда
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownClothes">
                    <a class="dropdown-item" href="{% url 'admin_panel:all_clothes' %}">Весть товар</a>
                    <a class="dropdown-item" href="{% url 'admin_panel:new_clothes' %}">Создать новый товар</a>
                </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownOrder" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Заказы
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownOrder">
                    <a class="dropdown-item" href="{% url 'admin_panel:all_order' %}">Все заказы</a>
                    <a class="dropdown-item" href="{% url 'admin_panel:all_order_with_param' 1 %}">Быстрые заказы</a>
                    <a class="dropdown-item" href="{% url 'admin_panel:all_order_with_param' 2 %}">Заполненый заказ</a>
                    <a class="dropdown-item" href="{% url 'admin_panel:all_order_with_param' 3 %}">Выполненый заказ</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownUser" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Юзеры
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownUser">
                    <a class="dropdown-item" href="{% url 'user_permission:all_user' %}">Все юзеры</a>
                    <a class="dropdown-item" href="{% url 'user_permission:new_user' %}">Создать юзера</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user_permission:logout' %}">Выйти</a>
                  </li>
            </ul>
            </div>
        </nav>
        {% endblock %}
        {% block main %}
        {% endblock %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
{% block script %}
{% endblock %}
</body>
</html>