crm/admin_panel/urls.py
from django.urls import path

from .views import (NewClothesView, UpdateClothesView, 
                    AllClothesView, AllOrderView, 
                    CompleteOrderView,RemoveClothesView)

app_name = 'admin_panel'

urlpatterns = [
    path('new_clothes/', NewClothesView.as_view(), name='new_clothes'),
    path('update_clohes/<int:pk>/', UpdateClothesView.as_view(), name='update_clothes'),
    path('remove_clothes/<int:pk>/', RemoveClothesView.as_view(), name='remove_clothes'),
    path('all_clothes/', AllClothesView.as_view(), name='all_clothes'),
    path('all_order/',AllOrderView.as_view(), name='all_order'),
    path('all_order/<int:filter>/',AllOrderView.as_view(), name='all_order_with_param'),
    path('complete_order/', CompleteOrderView.as_view(), name='complete_order'),
]

crm/crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('admin_panel.urls')),
    path('', include('user_permission.urls')),
]


urlpatterns += static( settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crm/admin_panel/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.

class Image(models.Model):
    class Meta:
        db_table='images'

    img = models.ImageField(upload_to = 'media/', verbose_name='Фотография профиля', default='../static/img/noimage.jpg', null=False,blank=False)

class SizeClothes(models.Model):
    class Meta:
        db_table='sizes_clothes'
    
    name_size = models.CharField(max_length=120, null=False,blank=False)
    datetime = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return '{}'.format(self.name_size)

class ColorClothes(models.Model):
    class Meta:
        db_table='colors_clothes'

    name_color = models.CharField(max_length=120,null=False, blank=False)

    def __str__(self):
        return '{}'.format(self.name_color)

class ClothesView(models.Model):
    class Meta:
        db_table ='clothes_views'
        ordering = ('datetime', 'enabled',)

    class TYPE_CLOTHES:
        TSHIRT=1
        HOODIE=2
        SHIRT=3
    
    CHOICE_TYPE_CLOTHES = (
        (TYPE_CLOTHES.TSHIRT, 'Футболка'),
        (TYPE_CLOTHES.HOODIE, 'Толстовка'),
        (TYPE_CLOTHES.SHIRT, 'Майка')
    )
    name = models.CharField(max_length=120, null=False,blank=False)
    description = models.CharField(max_length=500,null=False,blank=False)
    datetime = models.DateTimeField(auto_now_add=True, auto_now=False)
    type_clothes = models.PositiveSmallIntegerField(choices=CHOICE_TYPE_CLOTHES, default=TYPE_CLOTHES.TSHIRT)
    enabled = models.BooleanField(default=True)
    #clothes = models.ManyToManyField(Clothes, related_name='clothes_view')
    old_price = models.FloatField(validators=[MinValueValidator(0),], default=0, blank=True, null=True)
    price = models.FloatField(validators=[MinValueValidator(0),],null=False,blank=False)
    count = models.PositiveSmallIntegerField()
    #img = models.ForeignKey(Image,on_delete=models.CASCADE)
    img = models.URLField(verbose_name='Фотография одежды', null=False,blank=False)
    size = models.ManyToManyField(SizeClothes,related_name='clothes')
    color = models.ManyToManyField(ColorClothes,related_name='clothes')

    def __str__(self):
        return 'ID: {}, name: {}'.format(self.id, self.name)
class ChooceClothes(models.Model):
    class Meta:
        db_table='chooces_clothes'

    datetime = models.DateTimeField(auto_now_add=True, auto_now=False)
    clothes = models.ForeignKey(ClothesView,on_delete=models.CASCADE, related_name='chooce_clothes', null=True)
    price = models.FloatField(validators=[MinValueValidator(0),],null=False,blank=False)
    
class Order(models.Model):
    class Meta:
        db_table='orders'
        ordering=('-datetime',)

    class TYPE_ORDER:
        FAST = 1
        FULL = 2

    CHOICES_TYPE_ORDER = (
        (TYPE_ORDER.FAST, 'Быстрый заказ'),
        (TYPE_ORDER.FULL, 'Полный заказ'),
    )
    
    email = models.EmailField(null=True, blank=True)
    phone = models.CharField(max_length=20)
    name = models.CharField(max_length=120)
    surname = models.CharField(max_length=120,null=True, blank=True)
    city = models.CharField(max_length=120, null=True, blank=True)
    address_novoi_poshti = models.CharField(max_length=500, null=True, blank=True)
    datetime = models.DateTimeField(auto_now_add=True, auto_now=False)
    chooce_clothes = models.ManyToManyField(ChooceClothes, related_name='order')
    complete = models.BooleanField(default=False,null=True, blank=True)
    price = models.FloatField(validators=[MinValueValidator(0),],null=False,blank=False, default=0)
    type_order = models.PositiveSmallIntegerField(choices=CHOICES_TYPE_ORDER, default=TYPE_ORDER.FAST)

    def __str__(self):
        return 'ID: {}, datetime: {}'.format(self.id, self.datetime)

crm/admin_panel/forms.py
from django import forms 
from .models import ClothesView

class ClothesForm(forms.ModelForm):
    class Meta:
        model = ClothesView
        fields = ['name', 'description', 'type_clothes', 'enabled',
                    'old_price', 'price', 'count', 'img']

    class SIZE:
        XS = 1
        S = 2
        M = 3
        L = 4
        XL = 5
        XXL = 6

    MULTI_CHOICE_SIZE = (
        (SIZE.XS, "XS"),
        (SIZE.S, "S"),
        (SIZE.M, "M"),
        (SIZE.L, "L"),
        (SIZE.XL, "XL"),
        (SIZE.XXL, "XXL"),
        )
    
    class COLOR:
        RED = 1
        BLACK = 2
        WHITE = 3
        YELLOW = 4
        GREY = 5
    
    MULTI_CHOICE_COLOR = (
        (COLOR.RED, 'красный'),
        (COLOR.BLACK, 'чорный'),
        (COLOR.WHITE, 'белый'),
        (COLOR.YELLOW, 'жолтый'),
        (COLOR.GREY, 'серый'),
    )
    size = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
                                         choices=MULTI_CHOICE_SIZE, required=True)
    color = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
                                         choices=MULTI_CHOICE_COLOR, required=True)
    

crm/admin_panel/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.base import View 
from django.views.generic.edit import FormView
from .models import  Order,ClothesView
from .forms import ClothesForm

# Create your views here.


class NewClothesView(CreateView, LoginRequiredMixin):
    model = ClothesView
    fields = ['name', 'description', 'type_clothes', 'enabled',
                'old_price', 'price', 'count', 'img', 'size', 'color']
    #form_class = ClothesForm
    template_name = 'clothes_pages/form_clothes.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_anonymous:
            return redirect('admin_panel:all_clothes')
        if request.user.permission_user == 3:
            return super(NewClothesView,self).dispatch(request, *args, **kwargs)
        return redirect('admin_panel:all_clothes')

    def get_success_url(self):
        return reverse('admin_panel:all_clothes')
    

class UpdateClothesView(UpdateView, LoginRequiredMixin):
    model = ClothesView 
    fields = ['name', 'description', 'type_clothes', 'enabled',
                'old_price', 'price', 'count', 'img', 'size', 'color']
    template_name = 'clothes_pages/form_clothes.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_anonymous:
            return redirect('admin_panel:all_clothes')
        if request.user.is_anonymous or request.user.permission_user == 3:
            return super(UpdateClothesView,self).dispatch(request, *args, **kwargs)
        return redirect('admin_panel:all_clothes')
    
    def get_success_url(self):
        return reverse('admin_panel:all_clothes')

class RemoveClothesView(View):
    model = ClothesView 
    
    def get(self,request,*args,**kwargs):
        try:
            self.model.objects.get(pk=kwargs['pk']).delete()
        except:
           return redirect('admin_panel:all_clothes') 
        return redirect('admin_panel:all_clothes')


class AllClothesView(ListView, LoginRequiredMixin):
    model = ClothesView
    context_object_name ='clothes_views'
    template_name = 'clothes_pages/all_clothes.html'

class AllOrderView(ListView, LoginRequiredMixin):
    model = Order
    template_name = 'orders_pages/order_page.html'
    context_object_name ='order_view'

    def get_queryset(self,*args,**kwargs):
        qs = super().get_queryset()
        try:
            if kwargs['filter'] == 1 or kwargs['filter'] == 2:
                return qs.filter(type_order=kwargs['filter'])
            if kwargs['filter'] == 3:
                return qs.filter(complete=True)
        except:
            return qs

class CompleteOrderView(View, LoginRequiredMixin):

    def get(self,*args,**kwargs):
        Order.objects.filter(id=kwargs['pk']).update(complete=kwargs['complete']) 
    

crm/admin_panel/templates/clothes_pages/all_clothes.html
{% extends 'base.html' %}
{% block main %}
    {% for clothesview in clothes_views %}
    <div class="row no-gutters">
        <div class="col-md-4">
          <img src="{{ clothesview.img}}" class="card-img img-thumbnail" alt="...">
        </div>
    <div class="card mb-3 col-md-8">
        <div class="card-body">
            <a href="{% url 'admin_panel:remove_clothes' clothesview.pk %}" type="button" class="close" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </a>
          <h5 class="card-title">{{clothesview.name}}</h5>
          <p class="card-text">{{clothesview.description}}</p>
          <p class="card-text">{% if clothesview.enabled %}Товар доступен на сайте{%else%}На сайте товара нету{%endif%}</p>
          <p class="cartd-text"><small class="text-muted">
            {% if clothesview.type_clothes == 1%}
            Футболка
            {% endif %}
            {% if clothesview.type_clothes == 2%}
            Толстовка
            {% endif %}
            {% if clothesview.type_clothes == 3%}
            Майка
            {% endif %}
          </small></p>
          <p class="card-text">
              {% if clothesview.old_price %}
                Цена без скидки: {{clothesview.old_price}}
              {% endif %}
              Цена: {{clothesview.price}}
          </p>
          <p class="card-text">
              РАзмеры:
              {% for size in clothesview.size.all %}
                {{size}}
              {% endfor %}
          </p>
          <p class="card-text">
              Цвета:
            {% for color in clothesview.color.all %}
              {{color}}
            {% endfor %}
        </p>
        <a href="{% url 'admin_panel:update_clothes' clothesview.pk %}">Изменить</a>
        </div>
    </div>
    </div>
    {%endfor%}
{% endblock %}

crm/admin_panel/templates/clothes_pages/form_clothes.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block name_page %}Создание одежды{% endblock %}
{% block main %}
<div class="container">  
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}

      <div class="row">
        <div class="col-md-6">
          {{ form.name | as_crispy_field }}
        </div>
        <div class="col-md-6">
          {{ form.description | as_crispy_field }}
        </div>
        <div class="col-md-4">
          {{ form.type_clothes | as_crispy_field }}
        </div>
        <div class="col-md-4">
          {{ form.old_price | as_crispy_field }}
        </div>
        <div class="col-md-4">
          {{ form.price | as_crispy_field }}
        </div>
        <div class="col-md-4">
          {{ form.count | as_crispy_field }}
        </div>
        <div class="col-md-4">
          {{ form.size | as_crispy_field }}
        </div>
        <div class="col-md-4">
          {{ form.color | as_crispy_field }}
        </div>
      </div>
      <div class="text-right">
        {{ form.img | as_crispy_field }}
      </div>
      <div class="form-row  justify-content-end">
        {{ form.enabled | as_crispy_field }}
        <input type="submit" value="Сохранить" class="btn btn-primary ">
      </div>	
    </form>
</div>

{% endblock %}