crm/crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('admin_panel.urls')),
    path('', include('user_permission.urls')),
]


urlpatterns += static( settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crm/user_permission/urls.py
from django.urls import path

from .views import (NewUserView, UpdateUserView, RemoveUserView,AllUserView,
                LoginUserView,LogoutUserView)

app_name = 'user_permission'

urlpatterns = [
    path('all_user/', AllUserView.as_view(), name='all_user'),
    path('new_user/', NewUserView.as_view(), name='new_user'),
    path('update_user/<int:pk>/', UpdateUserView.as_view(), name='update_user'),
    path('remove_user/<int:pk>/', RemoveUserView.as_view(), name='remove_user'),
    path('login/', LoginUserView.as_view(),name='login'),
    path('logout/',LogoutUserView.as_view(),name='logout')
]

crm/user_permission/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractUser
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail
# Create your models here.

class UserManager(BaseUserManager):
	"""Define a model manager for User model with no username field."""

	use_in_migrations = True

	def _create_user(self, email, password, **extra_fields):
		"""Create and save a User with the given email and password."""
		if not email:
			raise ValueError('The given email must be set')
		email = self.normalize_email(email)
		user = self.model(email=email, **extra_fields)
		user.set_password(password)
		user.save(using=self._db)
		return user

	def create_user(self, email, password=None, **extra_fields):
		"""Create and save a regular User with the given email and password."""
		extra_fields.setdefault('is_staff', False)
		extra_fields.setdefault('is_superuser', False)
		return self._create_user(email, password, **extra_fields)

	def create_superuser(self, email, password, **extra_fields):
		"""Create and save a SuperUser with the given email and password."""
		extra_fields.setdefault('is_staff', True)
		extra_fields.setdefault('is_superuser', True)

		if extra_fields.get('is_staff') is not True:
			raise ValueError('Superuser must have is_staff=True.')
		if extra_fields.get('is_superuser') is not True:
			raise ValueError('Superuser must have is_superuser=True.')

		return self._create_user(email, password, **extra_fields)




class User(AbstractUser):
	username = None 
	name = models.CharField(max_length=120, blank=True, null=True, verbose_name='Имя')
	surname = models.CharField(max_length=120, blank=True, null=True, verbose_name='Фамилия')
	email = models.EmailField(max_length=120, blank=False, null=False, unique=True, verbose_name='Email')
	

	is_staff = models.BooleanField(
		_('staff status'),
		default=False,
		help_text=_('Designates whether the user can log into this admin site.'),
		)
	is_active = models.BooleanField(
		_('active'),
		default=True,
		help_text=_(
			'Designates whether this user should be treated as active. ''Unselect this instead of deleting accounts.'
			),
		)

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = []

	objects = UserManager()
	class PERMISION_USER:
		MANAGER=1
		SUPPLIER=2
		STUFF=3
	
	CHOOICE_PREMISSIONS=(
		(PERMISION_USER.MANAGER, 'менеджер'),
        (PERMISION_USER.SUPPLIER, 'поставщик'),
        (PERMISION_USER.STUFF, 'админ')
	)
	
	permission_user = models.PositiveSmallIntegerField(choices=CHOOICE_PREMISSIONS, default=PERMISION_USER.MANAGER)
	
	def email_user(self, subject, message, from_email=None, **kwargs):
		send_mail(subject, message, from_email, [self.email], **kwargs)

	def __str__(self):
		return 'User: {} , type: {}, permission: {}'.format(self.name, self.surname, self.permission_user)

	class Meta:
		ordering = ['permission_user']

crm/user_permission/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import logout
from django.contrib.auth.views import  LoginView, LogoutView
from django.views.generic.base import View 
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView, DeletionMixin
from django.views.generic.list import ListView

from .models import User
# Create your views here.

class LogoutUserView(LogoutView):
    pass

class LoginUserView(LoginView):
    template_name = 'user/login.html'

class NewUserView(CreateView, LoginRequiredMixin):
    model = User
    template_name='user/form_user.html' 
    fields = ['name','surname','email','permission_user','password']

    def get_success_url(self):
        return reverse('user_permission:all_user')

    def dispatch(self, request, *args, **kwargs):
        if request.user.permission_user == 3:
            return super(NewUserView,self).dispatch(request, *args, **kwargs)
        return redirect('admin_panel:all_clothes')
    
    def get_context_data(self, **kwards):
        context = super(NewUserView, self).get_context_data(**kwards)
        context['name_button'] = 'Создать юзера'
        context['class_button'] = 'btn btn-primary'
        return context

class UpdateUserView(UpdateView, LoginRequiredMixin):
    model = User
    template_name='user/form_user.html'
    fields = ['name','surname','email','permission_user','password']
    
    def dispatch(self, request, *args, **kwargs):
        if request.user.permission_user == 3:
            return super(UpdateUserView,self).dispatch(request, *args, **kwargs)
        return redirect('admin_panel:all_clothes')
    
    def get_context_data(self, **kwards):
        context = super(UpdateUserView, self).get_context_data(**kwards)
        context['name_button'] = 'Обновить юзера'
        context['class_button'] = 'btn btn-primary'
        return context

class RemoveUserView(View, LoginRequiredMixin):
    model = User 
    template_name='user/form_user.html'
    def dispatch(self, request, *args, **kwargs):
        if request.user.permission_user == 3:
            return super(RemoveUserView,self).dispatch(request, *args, **kwargs)
        return redirect('admin_panel:all_clothes')

    def get(self,request,*args,**kwargs):
        print(kwargs)
        try:
            self.model.objects.get(pk=kwargs['pk']).delete()
        except:
           return redirect('user_permission:all_user') 
        return redirect('user_permission:all_user')

    def get_success_url(self):
        return reverse('user_permission:all_user')

class AllUserView(ListView, LoginRequiredMixin):
    model = User
    context_object_name ='users'
    template_name='user/all_user.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.permission_user == 3:
            return super(AllUserView,self).dispatch(request, *args, **kwargs)
        return redirect('admin_panel:all_clothes')

crm/user_permission/templates/user/all_user.html
{% extends 'base.html' %}

{% block main %}
<div class="container">
    <ul class="list-group list-group-flush"></ul>
    {% for user in users %}
    
        <li class="list-group-item"><a href="{% url 'user_permission:update_user' user.pk %}">Имя: {{user.name}},
                                     доступ: {% ifequal user.permission_user 1 %}
                                     Менеджер
                                     {%endifequal %}
                                     {% ifequal user.permission_user 2 %}
                                     Поставщик
                                     {%endifequal %}
                                     {% ifequal user.permission_user 3 %}
                                    Админ
                                     {%endifequal %}</a>

                                        <a href="{% url 'user_permission:remove_user' user.pk %}" type="button" class="close" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </a>
        

                                    </li>  
    {% endfor %}
    </ul>
</div>
{% endblock %}

crm/user_permission/templates/user/form_user.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block main %}
<div class="container">
    <form method="post">{% csrf_token %}
        {{ form|crispy}}
        <button type="submit" class="{{class_button}}">
            {{ name_button }}
        </button>
    </form>
</div>

{% endblock %}

crm/user_permission/templates/user/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block name_page %}Логин{% endblock %}
{% block css %}
<style>
	.main{
		background: white;
		border-radius: 10px;
	}



	.login_link{
		color: #4e2a84 !important;
	}

	h1,label{
		color: #401f68;
	}

	.form-check-label{
		color: #495057;
	}

</style>
{% endblock %}
{% block nav %}
{% endblock %}
{% block main %}

<div class="container main mt-5 pl-4 pr-4 ">
	<div class="row pb-3">
		<div class="col-12">

			{% if form.non_field_errors %}
			<div class="alert alert-danger" role="alert">
				{{ form.non_field_errors }}
			</div>

			{% endif %}
		</div>
		<div class="col-lg-6 col-12 offset-lg-3 ">
			{% if user.is_authenticated %}
			<p class='text-center h3'>Что такое, {{ user.name }}? Вы же уже авторизорваны. 
				Впрочем, всегда можно <a href="{% url 'logout' %}">выйти</a>.<br/><br/></p>
				{% else %}
				<form method="post" action="">
					{% for field in form %}
					<div class="form-row">
						{% csrf_token %}
						<div class="form-group col-12">
							{{ field | as_crispy_field }}
						</div>
						{% if field.help_text %}<div class="clearfix col-12">{{ field.help_text }}</div>{% endif %}
						{% if field.errors %}<div class="myerrors clearfix">{{ field.errors }}</div>{% endif %}
					</div>
					{% endfor %}
				
					<div class="form-row  justify-content-end">
						<input type="submit" value="Войти" class="btn btn-primary ">
					</div>			
				</form>
			</div>
				{% endif %}
		</div>





	</div>

	{% endblock %}